import type { Metadata } from "next";
import { Manrope, Playfair_Display } from "next/font/google";
import "./globals.css";

const manrope = Manrope({
    subsets: ["latin"],
    weight: ["200", "300", "400", "500", "600"],
    variable: "--font-manrope",
    display: "swap",
});

const playfair = Playfair_Display({
    subsets: ["latin"],
    weight: ["400", "600", "700"],
    style: ["normal", "italic"],
    variable: "--font-playfair",
    display: "swap",
});

export const metadata: Metadata = {
    title: "Aryan | Portfolio",
    // description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={`${manrope.variable} ${playfair.variable}`} >
            <body className="antialiased font-sans">
                {children}
            </body>
        </html>
    );
}
